
/* **** DO NOT EDIT - this file is generated by ARChitect2 ****
 *
 * Description: Header file declaring the compiler extensions for apex components 
 */

#ifndef _apexextensions_H_
#define _apexextensions_H_

#define APEX_NN_INSTRUCTION_ASSIGNW_NN_INSTRUCTION_ASSIGNW_PRESENT	1

// User extension aux register node_0
#define AR_NODE_0 0xfffff800
#pragma Aux_register(0xfffff800, name=>"node_0")

// User extension aux register node_1
#define AR_NODE_1 0xfffff801
#pragma Aux_register(0xfffff801, name=>"node_1")

// User extension instruction NN_ACCE
extern long NN_ACCE(long,long);
#pragma intrinsic(NN_ACCE,opcode=>7,sub_opcode=>0, effects=>"auxreg=0xfffff800:is_read:is_written; auxreg=0xfffff801:is_read:is_written")


#endif


